project:
  type: book
  output-dir: 'docs'
  execute-dir: project

book:
  title: "博士期间作业"
  author: "CongyuanHe"
  date: now
  
  chapters:
    - index.qmd
    - part: Bayesian.qmd
      chapters: 
        - bayesian hw 1.qmd
        - bayesian hw 2.qmd
        - bayesian hw 3.qmd
    - part: Survival.qmd
      chapters: 
        - survival hw 1.qmd
        - survival hw 2.qmd
    - part: Causal inference.qmd
      chapters: 
        - causal inference hw 1.qmd
    - part: Linear regression.qmd
      chapters: 
        - linear regression hw 3.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

